version: '3.8'
services:
  bot:
    build: .
    container_name: es_bot
    restart: always

    environment:
     BOT_TOKEN: ${ES_TOKEN}
     API_ID: ${ES_API_ID}
     API_HASH: ${ES_API_HASH}
    network_mode: host
    
    volumes:
     - type: volume
       source: bot_data
       target: /app

volumes:
 bot_data:         


